In [1]:
!pip install seaborn


In [10]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Activation function (Sigmoid)
def activation_func(value):
    return 1 / (1 + np.exp(-value))

# Perceptron Training
def perceptron_train(in_data, labels, alpha):
    x = np.array(in_data)
    y = np.array(labels)
    weights = np.random.random(x.shape[1])
    original = weights
    bias = np.random.random_sample()

    for key in range(x.shape[0]):
        a = activation_func(np.dot(weights, x[key]))
        yn = 0

        if a >= 0.7 and a<1.5:
            yn = 1
        elif a <= 0.7:
            yn = 0
        elif a >= 1.5:
            yn = 2

        weights = weights + alpha * (yn - y[key]) * x[key]
        print('Iteration ' + str(key) + ': ' + str(weights))

    print('Difference: ' + str(weights - original))
    return weights

# Perceptron Testing
def perceptron_test(in_data, weights):
    x = np.array(in_data)
    y = np.zeros(x.shape[0])

    for key in range(x.shape[0]):
        a = activation_func(np.dot(weights, x[key]))
        y[key] = 0
        print(a)

        if a >= 0.7 and a<1.5:
            yn = 1
        elif a <= 0.7:
            yn = 0
        elif a >= 1.5:
            yn = 2

    return y

# Accuracy Calculation
def score(result, labels):
    correct_ctr = np.sum(result == labels)
    score = (correct_ctr * 100) / len(labels)
    print('Score=' + str(score))

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Data Splitting (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

alpha = 0.01



In [15]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Activation function (Softmax)
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Perceptron Training
def perceptron_train(in_data, labels, alpha, epochs, num_classes):
    x = np.array(in_data)
    y = np.array(labels)
    weights = np.random.random((num_classes, x.shape[1]))
    original = weights.copy()
    bias = np.random.random_sample((num_classes,))

    for epoch in range(epochs):
        for i in range(x.shape[0]):
            a = softmax(np.dot(weights, x[i]) + bias)
            y_pred = np.argmax(a)

            weights[y[i]] = weights[y[i]] + alpha * (1 - a[y[i]]) * x[i]
            bias[y[i]] += alpha * (1 - a[y[i]])

        print(f'Epoch {epoch}: {weights}, {bias}')

    print('Difference: ' + str(weights - original))
    return weights, bias

# Perceptron Testing
def perceptron_test(in_data, weights, bias):
    x = np.array(in_data)
    y = np.zeros(x.shape[0])

    for i in range(x.shape[0]):
        a = softmax(np.dot(weights, x[i]) + bias)
        y[i] = np.argmax(a)
        print(a)

    return y

# Accuracy Calculation
def score(result, labels):
    correct_ctr = np.sum(result == labels)
    score = (correct_ctr * 100) / len(labels)
    print('Score=' + str(score))

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Data Splitting (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

alpha = 0.01
epochs = 100
num_classes = 3

# Train the perceptron
weights, bias = perceptron_train(X_train, y_train, alpha, epochs, num_classes)

# Test the perceptron
test_results = perceptron_test(X_test, weights, bias)

# Calculate and print accuracy
score(test_results, y_test)


Epoch 0: [[1.75485532 1.16853384 0.62967261 0.88483028]
 [1.77531075 1.62903985 1.08550605 0.76188011]
 [1.72741019 0.86942455 1.46559488 1.2819256 ]], [0.83533042 0.30311874 0.46282987]
Epoch 1: [[2.90799537 1.95319289 0.97093275 0.94248873]
 [2.88200908 2.13906433 1.88113024 1.00797024]
 [2.76886832 1.34535235 2.34463528 1.59920112]], [1.06647466 0.49130565 0.62180323]
Epoch 2: [[3.95943687 2.66780204 1.28307861 0.99534029]
 [3.92252372 2.61845532 2.63055466 1.23981308]
 [3.74966887 1.79334656 3.17204698 1.89732082]], [1.27726462 0.66808624 0.77143399]
Epoch 3: [[4.9586592  3.34603273 1.58080967 1.04591617]
 [4.92397041 3.0798955  3.35320804 1.46348019]
 [4.69435798 2.22464766 3.96855083 2.18396376]], [1.47771372 0.83811846 0.91553008]
Epoch 4: [[5.9251434  4.00119113 1.86989464 1.09520154]
 [5.89577086 3.52779837 4.05558243 1.68098479]
 [5.61177885 2.64330836 4.74162477 2.4618838 ]], [1.67174699 1.00307306 1.05545339]
Epoch 5: [[6.86522938 4.63763569 2.1521744  1.14350342]
 [6.84150

In [16]:
test_results

array([1., 0., 2., 1., 1., 0., 1., 2., 2., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 1., 2., 1., 2., 2., 2., 2., 2., 0., 1., 0., 0., 1., 0.,
       0., 2., 1., 0., 0., 0., 2., 1., 1., 0., 0.])

In [36]:
import numpy as np
import pandas as pd

In [37]:
df = pd.read_csv("/content/train.csv")
df

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245         -0.975300         -0.960322         -0.998807   
2            -0.995380         -0.967187         -0.978944         -0.996520   
3            -0.996091         -0.983403         -0.990675         -0.997099   
4            -0.998139         -0.980817         -0.990482         -0.998321   
...                ...               ...               ...               ...   
7347         -0.195387          0.039905          0.077078         -0.282301   
7348         -0.235309          0.004816          0.059280         -0.322552   
7349         -0.218218         -0.103822          0.274533         -0.304515   
7350         -0.219139         -0.111412          0.268893         -0.310487   
7351         -0.269270         -0.087212          0.177404         -0.377404   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...   
1            -0.974914         -0.957686         -0.943068  ...   
2            -0.963668         -0.977469         -0.938692  ...   
3            -0.982750         -0.989302         -0.938692  ...   
4            -0.979672         -0.990441         -0.942469  ...   
...                ...               ...               ...  ...   
7347          0.043616          0.060410          0.210795  ...   
7348         -0.029456          0.080585          0.117440  ...   
7349         -0.098913          0.332584          0.043999  ...   
7350         -0.068200          0.319473          0.101702  ...   
7351         -0.038678          0.229430          0.269013  ...   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                           -0.710304                    -0.112754   
1                           -0.861499                     0.053477   
2                           -0.760104                    -0.118559   
3                           -0.482845                    -0.036788   
4                           -0.699205                     0.123320   
...                               ...                          ...   
7347                        -0.880324                    -0.190437   
7348                        -0.680744                     0.064907   
7349                        -0.304029                     0.052806   
7350                        -0.344314                    -0.101360   
7351                        -0.740738                    -0.280088   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                                 0.030400                         -0.464761   
1                                -0.007435                         -0.732626   
2                                 0.177899                          0.100699   
3                                -0.012892                          0.640011   
4                                 0.122542                          0.693578   
...                                    ...                               ...   
7347                              0.829718                

In [38]:
df.isnull().sum()

tBodyAcc-mean()-X       0
tBodyAcc-mean()-Y       0
tBodyAcc-mean()-Z       0
tBodyAcc-std()-X        0
tBodyAcc-std()-Y        0
                       ..
angle(X,gravityMean)    0
angle(Y,gravityMean)    0
angle(Z,gravityMean)    0
subject                 0
Activity                0
Length: 563, dtype: int64

In [40]:
Y = df[['Activity' ]]
Y

Activity
0             STANDING
1             STANDING
2             STANDING
3             STANDING
4             STANDING
...                ...
7347  WALKING_UPSTAIRS
7348  WALKING_UPSTAIRS
7349  WALKING_UPSTAIRS
7350  WALKING_UPSTAIRS
7351  WALKING_UPSTAIRS

[7352 rows x 1 columns]

In [41]:
df['Activity-codes'] = df.Activity.astype('category').cat.codes
df1 = df.drop('Activity', axis=1)

In [44]:
x_col = df1.columns.to_list()
x_col.pop(-1)
x = df1[x_col]
x

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245         -0.975300         -0.960322         -0.998807   
2            -0.995380         -0.967187         -0.978944         -0.996520   
3            -0.996091         -0.983403         -0.990675         -0.997099   
4            -0.998139         -0.980817         -0.990482         -0.998321   
...                ...               ...               ...               ...   
7347         -0.195387          0.039905          0.077078         -0.282301   
7348         -0.235309          0.004816          0.059280         -0.322552   
7349         -0.218218         -0.103822          0.274533         -0.304515   
7350         -0.219139         -0.111412          0.268893         -0.310487   
7351         -0.269270         -0.087212          0.177404         -0.377404   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...   
1            -0.974914         -0.957686         -0.943068  ...   
2            -0.963668         -0.977469         -0.938692  ...   
3            -0.982750         -0.989302         -0.938692  ...   
4            -0.979672         -0.990441         -0.942469  ...   
...                ...               ...               ...  ...   
7347          0.043616          0.060410          0.210795  ...   
7348         -0.029456          0.080585          0.117440  ...   
7349         -0.098913          0.332584          0.043999  ...   
7350         -0.068200          0.319473          0.101702  ...   
7351         -0.038678          0.229430          0.269013  ...   

      fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
0                           -0.298676                        -0.710304   
1                           -0.595051                        -0.861499   
2                           -0.390748                        -0.760104   
3                           -0.117290                        -0.482845   
4                           -0.351471                        -0.699205   
...                               ...                              ...   
7347                        -0.588433                        -0.880324   
7348                        -0.390738                        -0.680744   
7349                         0.025145                        -0.304029   
7350                         0.063907                        -0.344314   
7351                        -0.387052                        -0.740738   

      angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                       -0.112754                              0.030400   
1                        0.053477                             -0.007435   
2                       -0.118559                              0.177899   
3                       -0.036788                             -0.012892   
4                        0.123320                              0.122542   
...                           ...                                   ...   
7347                    -0.190437            

In [45]:
Y = df[[ "Activity-codes"]]
Y

Activity-codes
0                  2
1                  2
2                  2
3                  2
4                  2
...              ...
7347               5
7348               5
7349               5
7350               5
7351               5

[7352 rows x 1 columns]

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,Y,test_size=0.1)
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((6616, 562), (736, 562), (6616, 1), (736, 1))

In [59]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model. add (Dense (16,activation='tanh', input_shape=(562,)))
model. add (Dense (32,activation='tanh'))
model. add (Dense(6,activation='softmax'))

In [54]:
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)


Shape of X: (150, 4)
Shape of Y: (7352, 1)


In [60]:
model.compile(loss = 'sparse_categorical_crossentropy' ,metrics =['accuracy'], optimizer="rmsprop")

In [61]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 16)                9008      
                                                                 
 dense_4 (Dense)             (None, 32)                544       
                                                                 
 dense_5 (Dense)             (None, 6)                 198       
                                                                 
Total params: 9750 (38.09 KB)
Trainable params: 9750 (38.09 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [62]:
model.fit(X_train, Y_train, epochs=25)

Epoch 1/25
207/207 [==============================] - 1s 1ms/step - loss: 0.6607 - accuracy: 0.7825
Epoch 2/25
207/207 [==============================] - 0s 1ms/step - loss: 0.2158 - accuracy: 0.9173
Epoch 3/25
207/207 [==============================] - 0s 1ms/step - loss: 0.1511 - accuracy: 0.9406
Epoch 4/25
207/207 [==============================] - 0s 1ms/step - loss: 0.1224 - accuracy: 0.9500
Epoch 5/25
207/207 [==============================] - 0s 1ms/step - loss: 0.1109 - accuracy: 0.9581
Epoch 6/25
207/207 [==============================] - 0s 1ms/step - loss: 0.0973 - accuracy: 0.9613
Epoch 7/25
207/207 [==============================] - 0s 1ms/step - loss: 0.0868 - accuracy: 0.9664
Epoch 8/25
207/207 [==============================] - 0s 1ms/step - loss: 0.0795 - accuracy: 0.9714
Epoch 9/25
207/207 [==============================] - 0s 1ms/step - loss: 0.0763 - accuracy: 0.9708
Epoch 10/25
207/207 [==============================] - 0s 1ms/step - loss: 0.0682 - accuracy: 0.9731

In [63]:
model.evaluate(X_test,Y_test)

23/23 [==============================] - 0s 1ms/step - loss: 0.0639 - accuracy: 0.9783


[0.06392531841993332, 0.97826087474823]