 **Single layered perceptron**

## importing lib

In [ ]:
!pip install seaborn


In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


## code


In [ ]:

# Activation function (Sigmoid)
def activation_func(value):
    return 1 / (1 + np.exp(-value))

# Perceptron Training
def perceptron_train(in_data, labels, alpha):
    x = np.array(in_data)
    y = np.array(labels)
    weights = np.random.random(x.shape[1])
    original = weights
    bias = np.random.random_sample()

    for key in range(x.shape[0]):
        a = activation_func(np.dot(weights, x[key]))
        yn = 0

        if a >= 0.7 and a<1.5:
            yn = 1
        elif a <= 0.7:
            yn = 0
        elif a >= 1.5:
            yn = 2

        weights = weights + alpha * (yn - y[key]) * x[key]
        print('Iteration ' + str(key) + ': ' + str(weights))

    print('Difference: ' + str(weights - original))
    return weights

# Perceptron Testing
def perceptron_test(in_data, weights):
    x = np.array(in_data)
    y = np.zeros(x.shape[0])

    for key in range(x.shape[0]):
        a = activation_func(np.dot(weights, x[key]))
        y[key] = 0
        print(a)

        if a >= 0.7 and a<1.5:
            yn = 1
        elif a <= 0.7:
            yn = 0
        elif a >= 1.5:
            yn = 2

    return y

# Accuracy Calculation
def score(result, labels):
    correct_ctr = np.sum(result == labels)
    score = (correct_ctr * 100) / len(labels)
    print('Score=' + str(score))

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Data Splitting (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

alpha = 0.01



runnning epochs

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Activation function (Softmax)
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Perceptron Training
def perceptron_train(in_data, labels, alpha, epochs, num_classes):
    x = np.array(in_data)
    y = np.array(labels)
    weights = np.random.random((num_classes, x.shape[1]))
    original = weights.copy()
    bias = np.random.random_sample((num_classes,))

    for epoch in range(epochs):
        for i in range(x.shape[0]):
            a = softmax(np.dot(weights, x[i]) + bias)
            y_pred = np.argmax(a)

            weights[y[i]] = weights[y[i]] + alpha * (1 - a[y[i]]) * x[i]
            bias[y[i]] += alpha * (1 - a[y[i]])

        print(f'Epoch {epoch}: {weights}, {bias}')

    print('Difference: ' + str(weights - original))
    return weights, bias

# Perceptron Testing
def perceptron_test(in_data, weights, bias):
    x = np.array(in_data)
    y = np.zeros(x.shape[0])

    for i in range(x.shape[0]):
        a = softmax(np.dot(weights, x[i]) + bias)
        y[i] = np.argmax(a)
        print(a)

    return y

# Accuracy Calculation
def score(result, labels):
    correct_ctr = np.sum(result == labels)
    score = (correct_ctr * 100) / len(labels)
    print('Score=' + str(score))

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Data Splitting (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

alpha = 0.01
epochs = 100
num_classes = 3

# Train the perceptron
weights, bias = perceptron_train(X_train, y_train, alpha, epochs, num_classes)

# Test the perceptron
test_results = perceptron_test(X_test, weights, bias)

# Calculate and print accuracy
score(test_results, y_test)


Epoch 0: [[2.2093834  1.09812168 1.31318035 0.79355354]
 [2.10701954 1.42269835 1.73642418 1.02509521]
 [2.18234233 1.32090861 1.73306036 1.18905071]], [0.2847591  0.77487192 0.80584921]
Epoch 1: [[3.47702557 1.96009959 1.68821009 0.85708133]
 [3.33935856 1.99220523 2.6198488  1.29821025]
 [3.34082863 1.84735378 2.71236315 1.54186763]], [0.53935224 0.98425051 0.98227939]
Epoch 2: [[4.64923225 2.7561566  2.03609798 0.91615722]
 [4.51267808 2.53453926 3.46217265 1.55871217]
 [4.44555865 2.34905744 3.64579108 1.87765077]], [0.77481568 1.18351742 1.15045823]
Epoch 3: [[5.77038498 3.51654904 2.36999134 0.97305061]
 [5.64705074 3.05903643 4.27777248 1.81108334]
 [5.51449404 2.83423174 4.54847349 2.20198887]], [1.00015311 1.37610943 1.31316213]
Epoch 4: [[6.85775456 4.253111   2.69498772 1.02863025]
 [6.74803199 3.56828574 5.07046445 2.05650472]
 [6.55283238 3.305265   5.42481496 2.51651182]], [1.21884775 1.56300946 1.47119111]
Epoch 5: [[7.91597092 4.96905072 3.01241985 1.08311416]
 [7.81788

final output

In [ ]:
test_results

array([1., 0., 2., 1., 1., 0., 1., 2., 2., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 1., 2., 1., 2., 2., 2., 2., 2., 0., 1., 0., 0., 1., 0.,
       0., 2., 1., 0., 0., 0., 2., 1., 1., 0., 0.])